
# TEST CARDS

GET http://localhost:3000/api/cards
Accept: application/json
###

GET http://localhost:3000/api/cards/52
Accept: application/json
Content-Type: application/json
###

GET http://localhost:3000/api/lists/11
/cards
###



# TEST LISTS

GET http://localhost:3000/api/lists
Accept: application/json
Content-Type: application/json
###

GET http://localhost:3000/api/lists/3
Accept: application/json
Content-Type: application/json
###