
# TEST CARDS

GET http://localhost:3000/cards
Accept: application/json
###

GET http://localhost:3000/cards/1
Accept: application/json
Content-Type: application/json
###





# TEST LISTS

GET http://localhost:3000/lists
Accept: application/json
Content-Type: application/json
###

GET http://localhost:3000/lists/1
Accept: application/json
Content-Type: application/json
###